version: "3"
services:
  web:
    build: ./app
    ports: 
      - "5000:5000"
    volumes: 
      - './app:/app'
    container_name: 'flask-container'
  redis:
    image: "redis:alpine"
    depends_on: 
      - web
    ports:
      - "6379:6379"
    container_name: 'redis-container'